Controllers/CategoriesController.cs
using Mealify.Data;
using Mealify.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Mealify.Controllers
{
	public class CategoriesController : Controller
	{
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationContext _context;

        public CategoriesController(UserManager<ApplicationUser> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public ActionResult Index()
        {
            List<Category> categories = new List<Category>();
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin"))
            {
                categories = _context.Categories!.Include(c => c.State).Include(c => c.Restaurant).ToList();
                return View(categories);
            }
            if (role.Contains("CompanyAdmin"))
            {
                categories = _context.Categories!.Include(c => c.State).Include(c => c.Restaurant).ToList();
                return View(categories);
            }
           
            return View(categories);
        }
        public ActionResult GetCategories(int id)
        {
            var categories = _context.Categories!.Include(c => c.State).Include(c => c.Restaurant).Where(r => r.RestaurantId == id).ToList();
            return View(categories);
        }

        public ActionResult Create()
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;

            ViewData["StateId"] = new SelectList(_context.Set<State>(), "Id", "Name");
            ViewData["Restaurant"] = new SelectList(_context.Set<Restaurant>(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,CompanyAdmin")]
        public ActionResult Create(Category category)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(category);
                    _context.SaveChanges();
                    return Ok("ok");
                    //eturn RedirectToAction(nameof(Index));
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();
                    var errorMessage = string.Join(" ", errorMessages);

                    return Ok(errorMessage);
                }
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }

        public ActionResult Edit(int? id)
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;
            var category = _context.Categories!.Include(c => c.Restaurant).Where(c => c.Id == id).FirstOrDefault();
            if (category == null)
            {
                return NotFound(); 
            }
            

            ViewData["StateId"] = new SelectList(_context.Set<State>(), "Id", "Name", category.StateId);
            ViewData["Restaurant"] = new SelectList(_context.Set<Restaurant>(), "Id", "Name", category.Restaurant.Id);
            return View(category);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,CompanyAdmin")]
        public ActionResult Edit(Category category)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Update(category);
                    _context.SaveChanges();
                    return Ok("ok");
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();
                    var errorMessage = string.Join(" ", errorMessages);

                    return Ok(errorMessage);
                }
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }

        public ActionResult Delete(int id)
        {

            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
                ViewBag.Id = id;
            }
            else
                ViewBag.Authorized = false;

            return View();
        }

        [Authorize(Roles = "Admin,CompanyAdmin")]
        [HttpPost]
        public ActionResult DeleteConfirmed(int Id)
        {
            try
            {
                var category = _context.Categories!.Where(c => c.Id == Id).FirstOrDefault();
                category!.StateId = 0;
                _context.Categories!.Update(category);
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                return Ok(e.Message);
            }
            return Ok("ok");
        }
    }
}

Controllers/FoodsController.cs
using Mealify.Data;
using Mealify.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace Mealify.Controllers
{
	public class FoodsController : Controller
	{
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationContext _context;

        public FoodsController(UserManager<ApplicationUser> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public ActionResult Index()
        {
            var food = _context.Foods!.Include(f => f.State).Include(f => f.Category).ToList();
            return View(food);
        }
        public ActionResult GetCategories(int id)
        {
            var categories = _context.Categories!.Include(c => c.State).Include(c => c.Restaurant).Where(r => r.RestaurantId == id).ToList();
            return View(categories);
        }

        public ActionResult Create()
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;

            ViewData["StateId"] = new SelectList(_context.Set<State>(), "Id", "Name");
            ViewData["Category"] = new SelectList(_context.Set<Category>(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,CompanyAdmin")]
        public ActionResult Create(Food food)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(food);
                    _context.SaveChanges();
                    return Ok("ok");
                    //eturn RedirectToAction(nameof(Index));
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();
                    var errorMessage = string.Join(" ", errorMessages);

                    return Ok(errorMessage);
                }
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }

        public ActionResult Edit(int? id)
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;
            var food = _context.Foods!.Include(c => c.Category).Where(c => c.Id == id).FirstOrDefault();
            if (food == null)
            {
                return NotFound();
            }


            ViewData["StateId"] = new SelectList(_context.Set<State>(), "Id", "Name", food.StateId);
            ViewData["Category"] = new SelectList(_context.Set<Category>(), "Id", "Name", food.Category.Id);
            return View(food);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,CompanyAdmin")]
        public ActionResult Edit(Food food)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Foods.Update(food);
                    _context.SaveChanges();
                    return Ok("ok");
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();
                    var errorMessage = string.Join(" ", errorMessages);

                    return Ok(errorMessage);
                }
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }

        public ActionResult Delete(int id)
        {

            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
                ViewBag.Id = id;
            }
            else
                ViewBag.Authorized = false;

            return View();
        }

        [Authorize(Roles = "Admin,CompanyAdmin")]
        [HttpPost]
        public ActionResult DeleteConfirmed(int Id)
        {
            try
            {
                var food = _context.Foods!.Where(c => c.Id == Id).FirstOrDefault();
                food!.StateId = 0;
                _context.Foods!.Update(food);
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                return Ok(e.Message);
            }
            return Ok("ok");
        }
    }
}

Controllers/UsersController.cs
using Mealify.Data;
using Mealify.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace Mealify.Controllers
{
	public class UsersController : Controller
	{
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationContext _context;

        public UsersController(UserManager<ApplicationUser> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public ActionResult Index()
        {
            var users = _userManager.Users.Include(u => u.Company).Include(u => u.State).ToList();
            return View(users);
        }
        public ActionResult GetRestaurantUsers(int id)
        {
            List<ApplicationUser> users = new List<ApplicationUser>();
            var restaurants = _context.RestaurantUsers.Where(ru => ru.RestaurantId == id).ToList();
            foreach (var item in restaurants)
            {
                var user = _userManager.Users.Include(u => u.Company).Include(u => u.State).Where(u => u.Id == item.ApplicationUserId).FirstOrDefault();
                if (user != null)
                {
                    users.Add(user);
                }
            }
            return View(users);
        }

        public ActionResult Create()
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;

            ViewData["StateId"] = new SelectList(_context.Set<State>(), "Id", "Name");
            ViewData["Companies"] = new SelectList(_context.Set<Company>(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(ApplicationUser applicationUser, string password)
        {
            applicationUser.RegisterDate = DateTime.Now;
            try
            {
                if (ModelState.IsValid)
                {
                    var result= _userManager.CreateAsync(applicationUser, password).Result;
                    if (result.Succeeded)
                    {
                        return Ok("ok");
                    }
                    
                    //eturn RedirectToAction(nameof(Index));
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();
                    var errorMessage = string.Join(" ", errorMessages);

                    return Ok(errorMessage);
                }
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
            
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Mealify</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/Mealify.styles.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/style.css">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
        <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.1/js/dataTables.buttons.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.1/js/buttons.dataTables.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.1/js/buttons.html5.min.js"></script>

        <script>
            $(document).ready(function () {
                // This WILL work because we are listening on the 'document', 
                // for a click on an element with an ID of #test-element
                $(document).on("click", '[data-open="ajmodal"]', function (e) {
                    e.preventDefault();
                    let modalUrl = $(this).data('url');
                    let modalTitle = $(this).data('title');
                    $('h5#modalTitle').text(modalTitle);
                   // console.log(modalUrl);
                    $('#loadData').load(modalUrl);

                });
                $(document).on("click", '[data-send="1"]', function (e) {
                    let sendUrl = $(this).data('post-url');
                    let sendId = $('input#Id').val();
                    let formName = $(this).data('action');
                    let sendData = $('form#' + formName).serialize();
                    
                    $.post(sendUrl, sendData, function (data) {
                        if (data == 'ok') {
                            $('.postResult').html('<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Success! </strong>Operation Successfully Complated<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>');

                        } else {
                            $('.postResult').html('<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Error! </strong> ' + data +'<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>');
                        }
                    });
                });


                $("#genelModal").on("hidden.bs.modal", function () {
                    location.reload();
                });
               
            });
        </script>
    </head>
    <body>
        <div class="modal fade" id="genelModal" tabindex="-1" aria-labelledby="genelModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalTitle"></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div id="loadData" class="modal-body">
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-dark" id="sidebar-wrapper">
                <center>
                    <img width="120px" src="~/logoo.png" />
                    <div class="sidebar-heading border-bottom text-bg-dark p-3">Mealify</div>
                </center>

                <div class="list-group list-group-flush">
                    <a asp-controller="Home" asp-action="Index" asp-area="" class="bi bi-house list-group-item list-group-item-action list-group-item-dark p-3 text-center">&emsp;Home</a>
                    @if (User.Identity.IsAuthenticated)
                    {

                        <a asp-controller="Companies" asp-action="Index" asp-area="" class="bi bi-building list-group-item list-group-item-action list-group-item-dark p-3 text-center">&emsp;Companies</a>
                        <a asp-controller="Restaurants" asp-action="Index" asp-area="" class="bi bi-shop list-group-item list-group-item-action list-group-item-dark p-3 text-center">&emsp;Restaurants</a>
                        <a asp-controller="Categories" asp-action="Index" asp-area="" class="bi bi-list-ul list-group-item list-group-item-action list-group-item-dark p-3 text-center">&emsp;Categories</a>
                        <a asp-controller="Foods" asp-action="Index" asp-area="" class="list-group-item list-group-item-action list-group-item-dark p-3 text-center bi bi-cup-straw">&emsp;Food / Drink Items</a>
                        <a asp-controller="Users" asp-action="Index" asp-area="" class="list-group-item list-group-item-action list-group-item-dark p-3 text-center bi bi-people">&emsp;Users</a>
                        <a asp-controller="Home" asp-action="About" asp-area="" class="bi bi-info-circle list-group-item list-group-item-action list-group-item-dark p-3 text-center">&emsp;About / Contact</a>

                    }
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <span class="bi bi-list" id="sidebarToggle"></span>
                        <div class="container-fluid d-flex justify-content-center align-items-center">
                            <span class="fw-bolder fs-3 text">Mealify  - Admin Panel</span>
                        </div>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">

                                
                            @if (User.Identity.IsAuthenticated)
                            {

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle badge text-bg-secondary" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Active User : [@User.Identity.Name]</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="Login" asp-action="ResetPassword">Change Password</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-controller="Login" asp-action="Logout" onclick="return confirm('Are you sure you want to log out')">Logout</a>
                                    </div>
                                </li>

                            }
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle badge text-bg-secondary" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Active User : None</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="Login" asp-action="Index">Login</a>
                                    </div>
                                </li>
                                
                            }
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
    </html>