Models/Restaurant.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Mealify.Models
{
    public class Restaurant
    {
        public int Id { get; set; }

        [StringLength(200, MinimumLength = 2)]
        [Column(TypeName = "nvarchar(200)")]
        public string Name { get; set; } = "";

        [Phone]
        [Column(TypeName = "varchar(30)")]
        public string Phone { get; set; } = "";

        [Column(TypeName = "char(5)")]
        [StringLength(5, MinimumLength = 5)]
        [DataType(DataType.PostalCode)]
        public string PostalCode { get; set; } = "";

        [StringLength(200, MinimumLength = 5)]
        [Column(TypeName = "nvarchar(200)")]
        public string AddressDetail { get; set; } = "";

        [DataType(DataType.DateTime)]
        [Column(TypeName = "smalldatetime")]
        public DateTime RegisterDate { get; set; }

        public int CompanyId { get; set; }
        public byte StateId { get; set; }

        [ForeignKey("StateId")]
        public State? State { get; set; }
        [ForeignKey("CompanyId")]
        public Company? Company { get; set; }

        public List<Category>? Categories { get; set; }
    }
}

Controllers/CategoriesController.cs
using Mealify.Data;
using Mealify.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Mealify.Controllers
{
	public class CategoriesController : Controller
	{
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationContext _context;

        public CategoriesController(UserManager<ApplicationUser> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public ActionResult Index()
        {
            List<Category> categories = new List<Category>();
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin"))
            {
                categories = _context.Categories!.Include(c => c.State).Include(c => c.Restaurant).ToList();
                return View(categories);
            }
            if (role.Contains("CompanyAdmin"))
            {
                categories = _context.Categories!.Include(c => c.State).Include(c => c.Restaurant).ToList();
                return View(categories);
            }
           
            return View(categories);
        }
        public ActionResult GetCategories(int id)
        {
            var categories = _context.Categories!.Include(c => c.State).Include(c => c.Restaurant).Where(r => r.RestaurantId == id).ToList();
            return View(categories);
        }

        public ActionResult Create()
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;

            ViewData["StateId"] = new SelectList(_context.Set<State>(), "Id", "Name");
            ViewData["Restaurant"] = new SelectList(_context.Set<Restaurant>(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,CompanyAdmin")]
        public ActionResult Create(Category category)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(category);
                    _context.SaveChanges();
                    return Ok("ok");
                    //eturn RedirectToAction(nameof(Index));
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();
                    var errorMessage = string.Join(" ", errorMessages);

                    return Ok(errorMessage);
                }
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }

        public ActionResult Edit(int? id)
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;
            var category = _context.Categories!.Include(c => c.Restaurant).Where(c => c.Id == id).FirstOrDefault();
            if (category == null)
            {
                return NotFound(); 
            }
            

            ViewData["StateId"] = new SelectList(_context.Set<State>(), "Id", "Name", category.StateId);
            ViewData["Restaurant"] = new SelectList(_context.Set<Restaurant>(), "Id", "Name", category.Restaurant.Id);
            return View(category);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,CompanyAdmin")]
        public ActionResult Edit(Category category)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Update(category);
                    _context.SaveChanges();
                    return Ok("ok");
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();
                    var errorMessage = string.Join(" ", errorMessages);

                    return Ok(errorMessage);
                }
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }

        public ActionResult Delete(int id)
        {

            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
                ViewBag.Id = id;
            }
            else
                ViewBag.Authorized = false;

            return View();
        }

        [Authorize(Roles = "Admin,CompanyAdmin")]
        [HttpPost]
        public ActionResult DeleteConfirmed(int Id)
        {
            try
            {
                var category = _context.Categories!.Where(c => c.Id == Id).FirstOrDefault();
                category!.StateId = 0;
                _context.Categories!.Update(category);
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                return Ok(e.Message);
            }
            return Ok("ok");
        }
    }
}

Controllers/RestaurantsController.cs
using System.Data;
using Mealify.Data;
using Mealify.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace Mealify.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationContext _context;

        public RestaurantsController(UserManager<ApplicationUser> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public ActionResult Index()
        {
            List<Restaurant> restaurants = new List<Restaurant>();
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin"))
            {
                restaurants = _context.Restaurants!.Include(r => r.State).Include(r => r.Company).ToList();
            }
            else if (role.Contains("CompanyAdmin"))
            {
                restaurants = _context.Restaurants!.Include(r => r.State).Include(r => r.Company).Where(r => r.Company!.ParentCompanyId == activeUser.CompanyId).ToList();

            }
            else if (role.Contains("RestaurantAdmin"))
            {
                List<RestaurantUser> restaurantUsers = _context.RestaurantUsers!.Include(ru => ru.Restaurant).Include(ru => ru.Restaurant!.Company).Where(ru => ru.ApplicationUserId == activeUser.Id).ToList();
                ViewData["RestaurantUsers"] = restaurantUsers;
            }
            return View(restaurants);
        }

        public ActionResult GetRestaurants(int id)
        {
            var restaurant = _context.Restaurants!.Include(r => r.State).Include(r => r.Company).Where(r => r.CompanyId == id).ToList();
            return View(restaurant);
        }

        public ActionResult AddRestaurantUser(int restaurantId)
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;
            var users = _userManager.Users.Where(u => u.StateId == 1).ToList();
            return View(users);
        }


        public ActionResult Create()
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewData["StateId"] = new SelectList(_context.Set<State>(), "Id", "Name");
                ViewData["CompanyId"] = new SelectList(_context.Set<Company>(), "Id", "Name");
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin,CompanyAdmin")]
        public ActionResult Create(Restaurant restaurant)
        {
            restaurant.RegisterDate = DateTime.Now;
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(restaurant);
                    _context.SaveChanges();
                    return Ok("ok");
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();
                    var errorMessage = string.Join(" ", errorMessages);

                    return Ok(errorMessage);
                }
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }

        // GET: RestaurantsController/Edit/5
        public ActionResult Edit(int id)
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Id = id;
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;
            var restaurant = _context.Restaurants!.Include(r => r.Company).Include(r => r.State).Where(r => r.Id == id).FirstOrDefault();
            if (restaurant == null)
                return NotFound();

            ViewData["StateId"] = new SelectList(_context.Set<State>(), "Id", "Name", restaurant.StateId);
            return View(restaurant);
        }

        // POST: RestaurantsController/Edit/5
        [HttpPost]
        public ActionResult Edit(Restaurant restaurant)
        {
            restaurant.RegisterDate = DateTime.Now;
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Update(restaurant);
                    _context.SaveChanges();
                    return Ok("ok");
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();
                    var errorMessage = string.Join(" ", errorMessages);

                    return Ok(errorMessage);
                }
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }

        }

        // GET: RestaurantsController/Delete/5
        public ActionResult Delete(int id)
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
                ViewBag.Id = id;
            }
            else
                ViewBag.Authorized = false;

            return View();
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var restaurant = _context.Restaurants!.Where(r => r.Id == id).FirstOrDefault();
                restaurant!.StateId = 0;
                _context.Restaurants!.Update(restaurant);
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                return Ok(e.Message);
            }
            return Ok("ok");
        }
    }
}

Controllers/UsersController.cs
using Mealify.Data;
using Mealify.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace Mealify.Controllers
{
	public class UsersController : Controller
	{
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationContext _context;

        public UsersController(UserManager<ApplicationUser> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public ActionResult Index()
        {
            var users = _userManager.Users.Include(u => u.Company).Include(u => u.State).ToList();
            return View(users);
        }
        public ActionResult GetRestaurantUsers(int id)
        {
            List<ApplicationUser> users = new List<ApplicationUser>();
            var restaurants = _context.RestaurantUsers.Where(ru => ru.RestaurantId == id).ToList();
            foreach (var item in restaurants)
            {
                var user = _userManager.Users.Include(u => u.Company).Include(u => u.State).Where(u => u.Id == item.ApplicationUserId).FirstOrDefault();
                if (user != null)
                {
                    users.Add(user);
                }
            }
            return View(users);
        }

        public ActionResult Create()
        {
            var activeUser = _userManager.GetUserAsync(User).Result;
            var role = _userManager.GetRolesAsync(activeUser).Result;
            if (role.Contains("Admin") || role.Contains("CompanyAdmin"))
            {
                ViewBag.Authorized = true;
            }
            else
                ViewBag.Authorized = false;

            ViewData["StateId"] = new SelectList(_context.Set<State>(), "Id", "Name");
            ViewData["Companies"] = new SelectList(_context.Set<Company>(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(ApplicationUser applicationUser, string password)
        {
            applicationUser.RegisterDate = DateTime.Now;
            try
            {
                if (ModelState.IsValid)
                {
                    var result= _userManager.CreateAsync(applicationUser, password).Result;
                    if (result.Succeeded)
                    {
                        return Ok("ok");
                    }
                    
                    //eturn RedirectToAction(nameof(Index));
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();
                    var errorMessage = string.Join(" ", errorMessages);

                    return Ok(errorMessage);
                }
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
            
            return View();
        }

    }
}

Views/Restaurants/AddRestaurantUser.cshtml
@*
        For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
    @*
        For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}


@model Mealify.Models.ApplicationUser

@if (!ViewBag.Authorized)
{
    <p class="text-center">Seems like <strong class="text-bg-danger">&nbsp;YOU ARE NOT AUTHORIZED&nbsp;</strong> for this action !!!</p>
}
@if (ViewBag.Authorized)
{
    <div class="row">
        <div class="col-md-12">
            <div class="postResult"></div>
            <form id="addRestaurantUser" onsubmit="return false">
                <div class="form-group">
                    <label asp-for="CompanyId" class="control-label"></label>
                    <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.Companies">
                    </select>
                </div><br />
                <div class="form-group">
                    <input data-send="1" data-post-url="Restaurants/AddRestaurantUser" data-action="addRestaurantUser" type="submit" value="Add User" class="btn btn-primary float-end" />
                </div>
            </form>
        </div>
    </div>
}

Views/Restaurants/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}


@model Mealify.Models.Restaurant

@if (!ViewBag.Authorized)
{
    <p class="text-center">Seems like <strong class="text-bg-danger">&nbsp;YOU ARE NOT AUTHORIZED&nbsp;</strong> for this action !!!</p>
}
@if (ViewBag.Authorized)
{
    <div class="row">
        <div class="col-md-12">
            <div class="postResult"></div>
            <form id="createRestaurant" onsubmit="return false">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PostalCode" class="control-label"></label>
                    <input asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AddressDetail" class="control-label"></label>
                    <input asp-for="AddressDetail" class="form-control" />
                    <span asp-validation-for="AddressDetail" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StateId" class="control-label"></label>
                    <select asp-for="StateId" class="form-control" asp-items="ViewBag.StateId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="CompanyId" class="control-label"></label>
                    <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.CompanyId"></select>
                    <span asp-validation-for="CompanyId" class="text-danger"></span>
                </div><br />
                <div class="form-group">
                    <input data-send="1" data-post-url="Restaurants/Create" data-action="createRestaurant" type="submit" value="Create" class="btn btn-primary float-end" />
                </div>
            </form>
        </div>
    </div>
}

Views/Restaurants/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Restaurants/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
    @model Mealify.Models.Restaurant
}

<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressDetail" class="control-label"></label>
                <input asp-for="AddressDetail" class="form-control" />
                <span asp-validation-for="AddressDetail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StateId" class="control-label"></label>
                <select asp-for="StateId" class="form-control" asp-items="ViewBag.StateId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Restaurants/Index.cshtml
@{
    ViewBag.State = "";
    ViewBag.Cls = "";
}
@model IEnumerable<Mealify.Models.Restaurant>


<script>$(document).ready(function () {
        $('#RestaurantTable').DataTable();
    });</script>

<h1 class="text-center" style="padding:30px">Restaurant List</h1>

@if (ViewBag.RestaurantUsers != null)
{
    <table id="RestaurantTable" class="table table-striped table-hover">

        <thead>
            <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Postal Code</th>
                <th>Address</th>
                <th>Register Date</th>
                <th>Company</th>
                <th>State</th>
                <th style="width:315px;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.RestaurantUsers)
            {
                if (@item.Restaurant.StateId == 0)
                {
                    ViewBag.State = "Deleted";
                    ViewBag.Cls = "btn-danger";

                }
                else if (@item.Restaurant.StateId == 1)
                {
                    ViewBag.State = "Active";
                    ViewBag.Cls = "btn-success";
                }
                else
                {
                    ViewBag.State = "Passive";
                    ViewBag.Cls = "btn-secondary";
                }
                <tr>
                    <td>@item.Restaurant.Name</td>
                    <td>@item.Restaurant.Phone</td>
                    <td>@item.Restaurant.PostalCode</td>
                    <td>@item.Restaurant.AddressDetail</td>
                    <td>@item.Restaurant.RegisterDate</td>
                    <td>@item.Restaurant.Company.Name</td>
                    <td><span class="btn @ViewBag.Cls btn-sm">@ViewBag.State</span></td>
                    <td>
                        <a asp-action="GetCategories" asp-controller="Categories" asp-route-id="@item.Restaurant.Id" class="btn btn-info btn-sm">Go to Categories</a>
                        <a asp-controller="Users" asp-action="GetRestaurantUsers" asp-route-id="@item.Restaurant.Id" class="btn btn-info btn-sm">See Users</a>
                        <a data-url="Restaurants/Edit/@item.Restaurant.Id" data-title="Update @item.Restaurant.Name" href="javascript:;" data-open="ajmodal" data-bs-toggle="modal" data-bs-target="#genelModal" class="btn btn-primary btn-sm">Edit</a>
                        <a data-url="Restaurants/Delete/@item.Restaurant.Id" data-title="Deleting @item.Restaurant.Name" href="javascript:;" data-open="ajmodal" data-bs-toggle="modal" data-bs-target="#genelModal" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>

            }
        </tbody>
    </table>
}
@if (ViewBag.RestaurantUsers == null)
{
    <a data-url="Restaurants/Create" data-title="Add New Restaurant" href="javascript:;" data-open="ajmodal" data-bs-toggle="modal" data-bs-target="#genelModal" class="btn btn-outline-primary btn-sm" style="margin:20px 0px 10px 0px">Create New</a>

    <table id="RestaurantTable" class="table table-striped table-hover">

        <thead>
            <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Postal Code</th>
                <th>Address</th>
                <th>Register Date</th>
                <th>Company</th>
                <th>State</th>
                <th style="width:315px;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                if (@item.State!.Id == 0)
                {
                    ViewBag.State = "Deleted";
                    ViewBag.Cls = "btn-danger";

                }
                else if (@item.State!.Id == 1)
                {
                    ViewBag.State = "Active";
                    ViewBag.Cls = "btn-success";
                }
                else
                {
                    ViewBag.State = "Passive";
                    ViewBag.Cls = "btn-secondary";
                }
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Phone</td>
                    <td>@item.PostalCode</td>
                    <td>@item.AddressDetail</td>
                    <td>@item.RegisterDate</td>
                    <td>@item.Company.Name</td>
                    <td><span class="btn @ViewBag.Cls btn-sm">@ViewBag.State</span></td>
                    <td>
                        <a asp-action="GetCategories" asp-controller="Categories" asp-route-id="@item.Id" class="btn btn-info btn-sm">Go to Categories</a>
                        <a asp-controller="Users" asp-action="GetRestaurantUsers" asp-route-id="@item.Id" class="btn btn-info btn-sm">See Users</a>
                        @*<a asp-controller="Restaurants" asp-action="AddRestaurantUser" asp-route-id="@item.Id" data-url="Restaurants/Edit/@item.Id" data-title="Update @item.Name" href="javascript:;" data-open="ajmodal" data-bs-toggle="modal" data-bs-target="#genelModal" class="btn btn-info btn-sm">Add Users</a>*@
                        <a data-url="Restaurants/AddRestaurantUser/@item.Id" data-title="Add User For @item.Name " href="javascript:;" data-open="ajmodal" data-bs-toggle="modal" data-bs-target="#genelModal" class="btn btn-info btn-sm">Add Users</a>
                        <a data-url="Restaurants/Edit/@item.Id" data-title="Update @item.Name" href="javascript:;" data-open="ajmodal" data-bs-toggle="modal" data-bs-target="#genelModal" class="btn btn-primary btn-sm">Edit</a>
                        <a data-url="Restaurants/Delete/@item.Id" data-title="Deleting @item.Name" href="javascript:;" data-open="ajmodal" data-bs-toggle="modal" data-bs-target="#genelModal" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>

            }
        </tbody>
    </table>
}